FROM python:3.8.3-slim-buster

RUN pip install -U \
    pip \
    setuptools \
    wheel

WORKDIR /dogger

RUN useradd -m -r user && \
    chown user /project

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

USER user

ENTRYPOINT ["/", "--"]


